spring:
  application:
    name: trading-platform
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trading_platform}
    username: ${SPRING_DATASOURCE_USERNAME:trading}
    password: ${SPRING_DATASOURCE_PASSWORD:trading}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

market:
  stub-generator:
    delay: ${MARKET_STUB_GENERATOR_DELAY:10000}
    initial-delay: ${MARKET_STUB_GENERATOR_INITIAL_DELAY:10000}
